// 50 câu hỏi trắc nghiệm - Kỹ năng quản lý
// a = chỉ số đáp án đúng (0-based). level: "easy" | "medium" | "hard"
const QUESTIONS = [
  {
    g: "Lãnh đạo",
    level: "easy",
    q: "Nhóm mất động lực vì mục tiêu dự án quá xa. Người quản lý nên làm gì trước tiên?",
    o: [
      "Nhắc mọi người phải cố gắng hơn",
      "Làm rõ mục tiêu, ý nghĩa và các mốc ngắn hạn",
      "Tự làm phần việc quan trọng nhất",
      "Tăng số lần kiểm tra",
    ],
    a: 1,
    e: "Chia mục tiêu xa thành mốc ngắn hạn và làm rõ ý nghĩa giúp nhóm thấy tiến bộ và lấy lại động lực.",
  },
  {
    g: "Lãnh đạo",
    level: "easy",
    q: "Một thành viên có ý tưởng tốt nhưng ngại phát biểu. Cách lãnh đạo phù hợp nhất là?",
    o: [
      "Bỏ qua vì họ không chủ động",
      "Yêu cầu họ trình bày ngay trước đông người",
      "Tạo cơ hội an toàn để họ chia sẻ và ghi nhận đóng góp",
      "Giao toàn bộ dự án cho họ",
    ],
    a: 2,
    e: "An toàn tâm lý và sự ghi nhận là điều kiện để người ít nói đóng góp ý tưởng.",
  },
  {
    g: "Lãnh đạo",
    level: "easy",
    q: "Hành vi nào giúp xây dựng niềm tin tốt nhất?",
    o: [
      "Giữ lời hứa và nhất quán giữa lời nói với hành động",
      "Luôn đồng ý với nhân viên",
      "Không bao giờ thay đổi quyết định",
      "Chỉ tập trung vào kết quả",
    ],
    a: 0,
    e: "Niềm tin đến từ sự nhất quán và giữ cam kết, không phải từ việc chiều lòng hay cứng nhắc.",
  },
  {
    g: "Lãnh đạo",
    level: "easy",
    q: "Vai trò cốt lõi của người lãnh đạo trong nhóm là gì?",
    o: [
      "Làm nhiều việc nhất nhóm",
      "Định hướng, tạo điều kiện và dẫn dắt nhóm đạt mục tiêu",
      "Kiểm soát toàn bộ thông tin",
      "Giữ khoảng cách với nhân viên",
    ],
    a: 1,
    e: "Lãnh đạo là dẫn dắt và tạo điều kiện, không phải tự gánh hết việc.",
  },
  {
    g: "Lãnh đạo",
    level: "easy",
    q: "Khi nhóm đạt kết quả tốt, người quản lý nên?",
    o: [
      "Nhận công về mình",
      "Ghi nhận công khai đóng góp của nhóm và từng cá nhân",
      "Không nói gì để tránh tự mãn",
      "Chỉ khen người giỏi nhất",
    ],
    a: 1,
    e: "Ghi nhận đúng người, đúng việc củng cố động lực và hành vi tích cực.",
  },
  {
    g: "Lãnh đạo",
    level: "medium",
    q: "Nhóm gồm người mới chưa thạo việc nhưng rất nhiệt tình. Phong cách lãnh đạo phù hợp nhất là?",
    o: [
      "Trao quyền hoàn toàn",
      "Hướng dẫn cụ thể, kèm cặp sát trong giai đoạn đầu",
      "Chỉ giao việc rồi đánh giá cuối kỳ",
      "Để nhóm tự tìm cách",
    ],
    a: 1,
    e: "Năng lực thấp – động lực cao cần phong cách chỉ dẫn/kèm cặp, trao quyền dần khi năng lực tăng.",
  },

  {
    g: "Giao tiếp",
    level: "easy",
    q: "Nhân viên giải thích một vấn đề phức tạp. Người quản lý nên làm gì để lắng nghe chủ động?",
    o: [
      "Ngắt lời để tiết kiệm thời gian",
      "Vừa nghe vừa kiểm tra điện thoại",
      "Tóm tắt lại và đặt câu hỏi làm rõ",
      "Đưa ra giải pháp ngay",
    ],
    a: 2,
    e: "Lắng nghe chủ động gồm tập trung, tóm tắt lại và hỏi làm rõ trước khi phản hồi.",
  },
  {
    g: "Giao tiếp",
    level: "easy",
    q: "Khi giao một nhiệm vụ quan trọng, cách truyền đạt nào hiệu quả nhất?",
    o: [
      "Nói càng nhiều càng tốt",
      "Nêu rõ kết quả mong đợi, thời hạn và tiêu chuẩn",
      "Chỉ gửi tên nhiệm vụ",
      "Để nhân viên tự đoán ưu tiên",
    ],
    a: 1,
    e: "Thông điệp rõ ràng phải trả lời: làm gì, đạt mức nào, khi nào xong.",
  },
  {
    g: "Giao tiếp",
    level: "easy",
    q: "Khi cần góp ý về một lỗi, cách phản hồi phù hợp nhất là?",
    o: [
      "Chỉ trích tính cách của người làm",
      "Nói chung chung để tránh khó xử",
      "Nêu hành vi cụ thể, tác động và hướng cải thiện",
      "Phê bình trước cả nhóm",
    ],
    a: 2,
    e: "Phản hồi hiệu quả tập trung vào hành vi và tác động, kèm đề xuất cải thiện.",
  },
  {
    g: "Giao tiếp",
    level: "easy",
    q: "Dấu hiệu nào cho thấy thông điệp đã được truyền đạt thành công?",
    o: [
      "Người nghe im lặng",
      "Người nghe diễn đạt lại đúng nội dung và bước tiếp theo",
      "Người nói đã nói hết ý",
      "Cuộc họp kết thúc đúng giờ",
    ],
    a: 1,
    e: "Giao tiếp chỉ hoàn tất khi người nhận hiểu đúng; phản hồi lại là cách kiểm chứng.",
  },
  {
    g: "Giao tiếp",
    level: "easy",
    q: "Với một tin nhạy cảm liên quan đến cá nhân, kênh phù hợp nhất là?",
    o: [
      "Email gửi toàn công ty",
      "Trao đổi trực tiếp, riêng tư",
      "Đăng lên nhóm chat chung",
      "Nhờ người khác nói hộ",
    ],
    a: 1,
    e: "Việc nhạy cảm cần kênh riêng tư, hai chiều để giữ tôn trọng và làm rõ kịp thời.",
  },
  {
    g: "Giao tiếp",
    level: "easy",
    q: "Giao tiếp phi ngôn ngữ bao gồm yếu tố nào?",
    o: [
      "Ánh mắt, cử chỉ, giọng điệu",
      "Chỉ nội dung văn bản",
      "Số trang tài liệu",
      "Số lượng email gửi đi",
    ],
    a: 0,
    e: "Ánh mắt, tư thế, cử chỉ và giọng điệu chiếm phần lớn ấn tượng trong giao tiếp trực tiếp.",
  },
  {
    g: "Giao tiếp",
    level: "medium",
    q: "Trong cuộc họp, hai nhân viên tranh luận gay gắt và lạc chủ đề. Người chủ trì nên?",
    o: [
      "Để họ tranh luận đến khi xong",
      "Ghi nhận cả hai quan điểm, chốt tiêu chí quyết định và đưa cuộc họp về mục tiêu",
      "Kết thúc cuộc họp ngay",
      "Quyết định theo người nói to hơn",
    ],
    a: 1,
    e: "Người chủ trì điều tiết tiến trình: ghi nhận, làm rõ tiêu chí và kéo thảo luận về mục tiêu họp.",
  },

  {
    g: "Lập kế hoạch",
    level: "easy",
    q: "Mục tiêu nào gần với nguyên tắc SMART nhất?",
    o: [
      "Cải thiện dịch vụ thật tốt",
      "Tăng mức hài lòng khách hàng từ 80% lên 88% trong 3 tháng",
      "Cố gắng bán nhiều hơn",
      "Hoàn thành công việc sớm",
    ],
    a: 1,
    e: "SMART yêu cầu cụ thể, đo lường được và có mốc thời gian rõ ràng.",
  },
  {
    g: "Lập kế hoạch",
    level: "easy",
    q: "Khi có quá nhiều việc cần làm, bước phù hợp nhất là?",
    o: [
      "Làm việc dễ trước",
      "Ưu tiên theo mức độ quan trọng và khẩn cấp",
      "Làm tất cả cùng lúc",
      "Chờ đến khi có chỉ đạo",
    ],
    a: 1,
    e: "Ma trận quan trọng – khẩn cấp giúp phân bổ thời gian vào việc tạo giá trị cao nhất.",
  },
  {
    g: "Lập kế hoạch",
    level: "easy",
    q: "Một kế hoạch tốt nên được điều chỉnh khi nào?",
    o: [
      "Không bao giờ",
      "Chỉ khi dự án thất bại",
      "Khi dữ liệu, rủi ro hoặc điều kiện thực tế thay đổi đáng kể",
      "Mỗi ngày dù không có thay đổi",
    ],
    a: 2,
    e: "Kế hoạch là công cụ, cần cập nhật khi giả định hoặc điều kiện thay đổi.",
  },
  {
    g: "Lập kế hoạch",
    level: "easy",
    q: "Chữ 'M' trong nguyên tắc SMART nghĩa là gì?",
    o: [
      "Measurable – đo lường được",
      "Modern – hiện đại",
      "Manual – thủ công",
      "Maximum – tối đa",
    ],
    a: 0,
    e: "SMART: Specific, Measurable, Achievable, Relevant, Time-bound.",
  },
  {
    g: "Lập kế hoạch",
    level: "easy",
    q: "Cột mốc (milestone) trong kế hoạch dùng để làm gì?",
    o: [
      "Tăng số lượng cuộc họp",
      "Đánh dấu điểm kiểm tra tiến độ quan trọng",
      "Thay thế mục tiêu",
      "Ghi nhận chi phí",
    ],
    a: 1,
    e: "Milestone là điểm kiểm tra giúp phát hiện lệch tiến độ sớm.",
  },
  {
    g: "Lập kế hoạch",
    level: "easy",
    q: "Quản trị rủi ro trong lập kế hoạch nên làm khi nào?",
    o: [
      "Sau khi rủi ro xảy ra",
      "Ngay từ khi lập kế hoạch, kèm phương án dự phòng",
      "Chỉ khi cấp trên yêu cầu",
      "Cuối dự án",
    ],
    a: 1,
    e: "Nhận diện rủi ro sớm và chuẩn bị phương án dự phòng rẻ hơn nhiều so với xử lý sự cố.",
  },

  {
    g: "Tổ chức & phân công",
    level: "easy",
    q: "Nguyên tắc quan trọng nhất khi phân công công việc là?",
    o: [
      "Chia đều số lượng việc cho mọi người",
      "Giao việc phù hợp năng lực, trách nhiệm và mục tiêu",
      "Giao việc khó cho người bận nhất",
      "Người quản lý giữ mọi quyết định",
    ],
    a: 1,
    e: "Phân công hiệu quả là ghép đúng người – đúng việc – đúng trách nhiệm.",
  },
  {
    g: "Tổ chức & phân công",
    level: "easy",
    q: "Khi trao quyền cho nhân viên, người quản lý nên?",
    o: [
      "Giao việc rồi không theo dõi",
      "Nói rõ quyền hạn, kết quả mong đợi và điểm kiểm tra",
      "Kiểm soát từng bước nhỏ",
      "Chỉ giao những việc không quan trọng",
    ],
    a: 1,
    e: "Trao quyền đi kèm ranh giới rõ ràng và các điểm kiểm tra đã thống nhất.",
  },
  {
    g: "Tổ chức & phân công",
    level: "easy",
    q: "Hai thành viên đang làm trùng một nhiệm vụ. Cách xử lý tốt nhất là?",
    o: [
      "Để họ tự giải quyết",
      "Làm rõ vai trò, trách nhiệm và đầu mối phối hợp",
      "Hủy nhiệm vụ",
      "Giao thêm người thứ ba",
    ],
    a: 1,
    e: "Trùng việc là vấn đề vai trò; làm rõ vai trò và đầu mối sẽ chấm dứt chồng chéo.",
  },
  {
    g: "Tổ chức & phân công",
    level: "easy",
    q: "Ủy quyền KHÔNG có nghĩa là?",
    o: [
      "Giao việc kèm quyền quyết định",
      "Phát triển năng lực nhân viên",
      "Chuyển toàn bộ trách nhiệm cuối cùng cho nhân viên",
      "Giải phóng thời gian cho việc ưu tiên",
    ],
    a: 2,
    e: "Người quản lý vẫn chịu trách nhiệm cuối cùng về kết quả dù đã ủy quyền.",
  },
  {
    g: "Tổ chức & phân công",
    level: "easy",
    q: "Khối lượng công việc của một thành viên vượt quá khả năng. Hành động đúng là?",
    o: [
      "Yêu cầu làm thêm giờ liên tục",
      "Xem lại thứ tự ưu tiên và tái phân bổ công việc",
      "Bỏ qua vì đó là việc của họ",
      "Giao thêm để rèn luyện",
    ],
    a: 1,
    e: "Quá tải kéo dài làm giảm chất lượng; cần điều chỉnh ưu tiên và phân bổ lại.",
  },
  {
    g: "Tổ chức & phân công",
    level: "easy",
    q: "Mục đích của việc mô tả rõ vai trò trong nhóm là?",
    o: [
      "Tăng thủ tục hành chính",
      "Tránh chồng chéo và bỏ sót trách nhiệm",
      "Giảm số nhân sự",
      "Hạn chế trao đổi",
    ],
    a: 1,
    e: "Vai trò rõ giúp mọi việc đều có người chịu trách nhiệm và không bị trùng lặp.",
  },
  {
    g: "Tổ chức & phân công",
    level: "medium",
    q: "Một việc quan trọng chỉ mình bạn làm thạo, nhưng lịch của bạn đã kín. Lựa chọn quản lý tốt nhất là?",
    o: [
      "Tự làm bằng mọi giá",
      "Hướng dẫn và giao dần cho một thành viên có tiềm năng, kèm điểm kiểm tra",
      "Hoãn việc vô thời hạn",
      "Thuê ngoài toàn bộ mà không bàn giao",
    ],
    a: 1,
    e: "Ủy quyền có kèm cặp vừa giải quyết tắc nghẽn hiện tại vừa xây năng lực dài hạn.",
  },

  {
    g: "Ra quyết định",
    level: "easy",
    q: "Trước một quyết định quan trọng, bước đầu tiên nên là?",
    o: [
      "Chọn phương án quen thuộc",
      "Xác định vấn đề và thu thập thông tin liên quan",
      "Hỏi người đông ý kiến nhất",
      "Trì hoãn để tránh rủi ro",
    ],
    a: 1,
    e: "Quyết định tốt bắt đầu từ việc xác định đúng vấn đề và có dữ liệu.",
  },
  {
    g: "Ra quyết định",
    level: "easy",
    q: "Hai phương án có lợi ích tương đương. Người quản lý nên làm gì?",
    o: [
      "Chọn ngẫu nhiên",
      "So sánh rủi ro, nguồn lực và tác động dài hạn",
      "Chọn phương án đắt hơn",
      "Không quyết định",
    ],
    a: 1,
    e: "Khi lợi ích ngang nhau, tiêu chí phân định là rủi ro, nguồn lực và tác động dài hạn.",
  },
  {
    g: "Ra quyết định",
    level: "easy",
    q: "Sau khi đã ra quyết định, trách nhiệm của người quản lý là?",
    o: [
      "Đổ lỗi nếu kết quả không tốt",
      "Theo dõi kết quả và điều chỉnh khi có bằng chứng cần thiết",
      "Không xem lại quyết định",
      "Thay đổi liên tục",
    ],
    a: 1,
    e: "Quyết định cần được theo dõi và hiệu chỉnh dựa trên bằng chứng thực tế.",
  },
  {
    g: "Ra quyết định",
    level: "easy",
    q: "Khi nào nên đưa nhóm cùng tham gia ra quyết định?",
    o: [
      "Khi cần cam kết thực thi cao và nhóm có thông tin liên quan",
      "Khi tình huống khẩn cấp cần phản ứng tức thì",
      "Khi quyết định thuộc thẩm quyền pháp lý cá nhân",
      "Khi muốn né trách nhiệm",
    ],
    a: 0,
    e: "Tham gia làm tăng chất lượng và cam kết, nhưng không phù hợp với tình huống khẩn cấp.",
  },
  {
    g: "Ra quyết định",
    level: "easy",
    q: "Tiêu chí quyết định nên được xác định khi nào?",
    o: [
      "Trước khi so sánh các phương án",
      "Sau khi đã chọn xong",
      "Khi có người phản đối",
      "Không cần thiết",
    ],
    a: 0,
    e: "Đặt tiêu chí trước giúp tránh thiên kiến hợp lý hóa lựa chọn có sẵn.",
  },
  {
    g: "Ra quyết định",
    level: "easy",
    q: "Rủi ro lớn nhất của việc trì hoãn quyết định là?",
    o: [
      "Tiết kiệm chi phí",
      "Mất cơ hội và kéo dài tác động tiêu cực",
      "Nhóm thêm tự chủ",
      "Giảm khối lượng công việc",
    ],
    a: 1,
    e: "Không quyết định cũng là một quyết định, thường kèm chi phí cơ hội.",
  },
  {
    g: "Ra quyết định",
    level: "hard",
    q: "Bạn đã đầu tư nhiều công sức vào một phương án, nhưng dữ liệu mới cho thấy nó khó đạt mục tiêu. Cách xử lý đúng đắn nhất?",
    o: [
      "Tiếp tục vì đã bỏ quá nhiều công sức",
      "Đánh giá lại dựa trên lợi ích – chi phí từ hiện tại trở đi và sẵn sàng đổi hướng",
      "Giao cho người khác tiếp tục",
      "Che bớt dữ liệu bất lợi",
    ],
    a: 1,
    e: "Tránh bẫy chi phí chìm: chỉ chi phí và lợi ích tương lai mới liên quan đến quyết định hiện tại.",
  },

  {
    g: "Giải quyết vấn đề",
    level: "easy",
    q: "Nhóm liên tục nộp báo cáo trễ. Việc đầu tiên nên làm là?",
    o: [
      "Phạt ngay",
      "Xác định vấn đề cụ thể và thu thập dữ liệu",
      "Thay toàn bộ nhóm",
      "Giảm yêu cầu chất lượng",
    ],
    a: 1,
    e: "Phải hiểu nguyên nhân trước khi áp dụng biện pháp.",
  },
  {
    g: "Giải quyết vấn đề",
    level: "easy",
    q: "Kỹ thuật “5 Whys” chủ yếu được dùng để?",
    o: [
      "Tìm người chịu lỗi",
      "Tìm nguyên nhân gốc rễ",
      "Tạo nhiều giải pháp sáng tạo",
      "Đánh giá ngân sách",
    ],
    a: 1,
    e: "5 Whys truy hỏi liên tiếp để đi từ triệu chứng đến nguyên nhân gốc.",
  },
  {
    g: "Giải quyết vấn đề",
    level: "easy",
    q: "Sau khi triển khai một giải pháp, bước nào quan trọng?",
    o: [
      "Kết thúc ngay",
      "Đo kết quả và rút kinh nghiệm",
      "Không nhắc lại vấn đề",
      "Chuyển trách nhiệm cho người khác",
    ],
    a: 1,
    e: "Đo lường và rút kinh nghiệm giúp giải pháp bền vững và không tái diễn vấn đề.",
  },
  {
    g: "Giải quyết vấn đề",
    level: "easy",
    q: "Thứ tự các bước giải quyết vấn đề hợp lý nhất là?",
    o: [
      "Xác định vấn đề → phân tích nguyên nhân → đề xuất giải pháp → thực hiện → đánh giá",
      "Thực hiện → xác định vấn đề → đánh giá",
      "Đề xuất giải pháp → xác định vấn đề → thực hiện",
      "Đánh giá → thực hiện → phân tích",
    ],
    a: 0,
    e: "Quy trình chuẩn đi từ nhận diện vấn đề đến đánh giá kết quả.",
  },
  {
    g: "Giải quyết vấn đề",
    level: "easy",
    q: "Mục đích chính của brainstorming là gì?",
    o: [
      "Chọn ngay giải pháp cuối cùng",
      "Tạo ra nhiều phương án trước khi đánh giá",
      "Phân công công việc",
      "Đánh giá năng lực cá nhân",
    ],
    a: 1,
    e: "Giai đoạn tạo ý tưởng cần tách khỏi giai đoạn phê bình, đánh giá.",
  },
  {
    g: "Giải quyết vấn đề",
    level: "easy",
    q: "Giải pháp 'chữa cháy' khác giải pháp gốc rễ ở điểm nào?",
    o: [
      "Chỉ xử lý triệu chứng tạm thời, vấn đề dễ tái diễn",
      "Luôn tốn kém hơn",
      "Không bao giờ được dùng",
      "Do cấp trên quyết định",
    ],
    a: 0,
    e: "Biện pháp tạm thời giúp cầm cự, nhưng cần đi kèm biện pháp xử lý nguyên nhân gốc.",
  },
  {
    g: "Giải quyết vấn đề",
    level: "medium",
    q: "Dữ liệu cho thấy lỗi tăng mạnh vào cuối tháng, trùng thời điểm tăng ca. Bước phân tích đúng tiếp theo là?",
    o: [
      "Kết luận ngay tăng ca gây ra lỗi và cấm tăng ca",
      "Kiểm chứng giả thuyết bằng dữ liệu bổ sung trước khi kết luận nguyên nhân",
      "Bỏ qua vì chỉ là trùng hợp",
      "Tăng mức phạt lỗi",
    ],
    a: 1,
    e: "Tương quan không đồng nghĩa nhân quả; cần kiểm chứng trước khi hành động.",
  },

  {
    g: "Tổng hợp",
    level: "easy",
    q: "Một dự án chậm tiến độ và tinh thần nhóm giảm. Cách tiếp cận tốt nhất là?",
    o: [
      "Chỉ tăng áp lực",
      "Làm rõ nguyên nhân, điều chỉnh kế hoạch và giao tiếp với nhóm",
      "Thay toàn bộ nhân sự",
      "Bỏ mục tiêu",
    ],
    a: 1,
    e: "Kết hợp phân tích nguyên nhân, điều chỉnh kế hoạch và giao tiếp minh bạch.",
  },
  {
    g: "Tổng hợp",
    level: "easy",
    q: "Một nhân viên có năng lực nhưng thường không rõ ưu tiên. Người quản lý nên?",
    o: [
      "Làm thay họ",
      "Làm rõ mục tiêu, thứ tự ưu tiên và quyền chủ động",
      "Kiểm tra mỗi 10 phút",
      "Không giao việc quan trọng",
    ],
    a: 1,
    e: "Vấn đề nằm ở sự rõ ràng về ưu tiên, không phải ở năng lực.",
  },
  {
    g: "Tổng hợp",
    level: "easy",
    q: "Dấu hiệu của quản lý hiệu quả nhất là?",
    o: [
      "Người quản lý luôn bận nhất",
      "Nhóm hiểu mục tiêu, phối hợp tốt và tạo ra kết quả bền vững",
      "Mọi quyết định đều do một người đưa ra",
      "Không có bất kỳ bất đồng nào",
    ],
    a: 1,
    e: "Hiệu quả quản lý thể hiện ở kết quả bền vững của nhóm, không ở mức độ bận rộn.",
  },
  {
    g: "Tổng hợp",
    level: "easy",
    q: "Mục đích của họp giao ban ngắn định kỳ là?",
    o: [
      "Đồng bộ tiến độ, phát hiện vướng mắc sớm",
      "Đánh giá lương thưởng",
      "Thay thế toàn bộ báo cáo",
      "Kéo dài thời gian làm việc",
    ],
    a: 0,
    e: "Nhịp họp ngắn giúp phát hiện rủi ro sớm và giữ nhóm đồng bộ.",
  },
  {
    g: "Tổng hợp",
    level: "easy",
    q: "Khi xảy ra xung đột trong nhóm, hướng xử lý xây dựng nhất là?",
    o: [
      "Tránh né cho đến khi tự hết",
      "Tập trung vào vấn đề và lợi ích chung, không vào cá nhân",
      "Chọn phe một bên",
      "Chuyển cả hai sang nhóm khác",
    ],
    a: 1,
    e: "Tách con người khỏi vấn đề và hướng vào lợi ích chung giúp xung đột trở nên xây dựng.",
  },
  {
    g: "Tổng hợp",
    level: "medium",
    q: "Nhân viên giỏi liên tục từ chối việc mới với lý do quá tải, trong khi số liệu cho thấy khối lượng ở mức trung bình. Bước đầu tiên nên là?",
    o: [
      "Kết luận họ thiếu hợp tác",
      "Trao đổi riêng để hiểu nguyên nhân thực sự trước khi kết luận",
      "Giao việc cho người khác và bỏ qua",
      "Đưa vào đánh giá kém",
    ],
    a: 1,
    e: "Số liệu chỉ ra sự khác biệt, đối thoại mới cho biết nguyên nhân (kỹ năng, động lực, vấn đề cá nhân).",
  },
  {
    g: "Tổng hợp",
    level: "hard",
    q: "Cấp trên yêu cầu rút ngắn 30% thời hạn dự án mà không thêm nguồn lực. Phản hồi quản lý chuyên nghiệp nhất là?",
    o: [
      "Đồng ý ngay để giữ hình ảnh",
      "Từ chối thẳng vì bất khả thi",
      "Trình bày phương án đánh đổi phạm vi – chất lượng – rủi ro kèm dữ liệu để cùng chọn",
      "Âm thầm giảm chất lượng để kịp hạn",
    ],
    a: 2,
    e: "Ràng buộc tam giác phạm vi – thời gian – nguồn lực: khi một yếu tố đổi, phải làm rõ đánh đổi bằng dữ liệu.",
  },
  {
    g: "Tổng hợp",
    level: "hard",
    q: "Chỉ số nhóm đạt KPI rất cao nhưng tỷ lệ nghỉ việc và than phiền nội bộ tăng. Cách đọc tình huống đúng nhất là?",
    o: [
      "Không vấn đề gì vì KPI vẫn tốt",
      "Kết quả ngắn hạn có thể đang đánh đổi bằng tính bền vững; cần rà soát cách thức đạt KPI",
      "Nên tăng KPI tiếp",
      "Thay người than phiền",
    ],
    a: 1,
    e: "Kết quả bền vững cần cả hiệu suất lẫn sức khỏe của nhóm; chỉ số hậu quả phải đọc cùng chỉ số dẫn dắt.",
  },
  {
    g: "Tổng hợp",
    level: "hard",
    q: "Bạn phải chọn giữa giải pháp cho kết quả nhanh nhưng tạo nợ quy trình, và giải pháp chậm hơn nhưng bền vững. Nguyên tắc quyết định hợp lý nhất là?",
    o: [
      "Luôn chọn phương án nhanh",
      "Luôn chọn phương án bền vững",
      "Căn cứ mức độ khẩn cấp, chi phí khắc phục về sau và cam kết kế hoạch trả 'nợ' nếu chọn phương án nhanh",
      "Để nhóm bỏ phiếu ngẫu nhiên",
    ],
    a: 2,
    e: "Chọn nhanh là hợp lệ nếu có ý thức về chi phí khắc phục và kế hoạch xử lý nợ quy trình.",
  },
  {
    g: "Tổng hợp",
    level: "hard",
    q: "Hai phòng ban mâu thuẫn vì mục tiêu KPI xung đột nhau. Giải pháp quản lý cấp hệ thống là?",
    o: [
      "Yêu cầu hai bên tự hòa giải",
      "Điều chỉnh mục tiêu chung và cơ chế phối hợp để loại bỏ xung đột cấu trúc",
      "Kỷ luật trưởng phòng",
      "Giảm KPI của cả hai",
    ],
    a: 1,
    e: "Xung đột do thiết kế mục tiêu phải được xử lý ở cấp hệ thống, không chỉ ở cấp quan hệ cá nhân.",
  },
];
