// 50 câu — Phiên bản Cơ Đốc
// 21 câu gốc từ bộ slide (giữ nguyên) + 29 câu quản trị Hội Thánh / nhóm tế bào
// a = chỉ số đáp án đúng (0-based)
const QUESTIONS = [
  // ===== LÃNH ĐẠO =====
  {
    g: "Lãnh đạo",
    q: "Nhóm mất động lực vì mục tiêu dự án quá xa. Người quản lý nên làm gì trước tiên?",
    o: [
      "Nhắc mọi người phải cố gắng hơn",
      "Làm rõ mục tiêu, ý nghĩa và các mốc ngắn hạn",
      "Tự làm phần việc quan trọng nhất",
      "Tăng số lần kiểm tra",
    ],
    a: 1,
    e: "Chia mục tiêu xa thành mốc ngắn hạn và làm rõ ý nghĩa giúp nhóm thấy tiến bộ và lấy lại động lực.",
  },
  {
    g: "Lãnh đạo",
    q: "Một thành viên có ý tưởng tốt nhưng ngại phát biểu. Cách lãnh đạo phù hợp nhất là?",
    o: [
      "Bỏ qua vì họ không chủ động",
      "Yêu cầu họ trình bày ngay trước đông người",
      "Tạo cơ hội an toàn để họ chia sẻ và ghi nhận đóng góp",
      "Giao toàn bộ dự án cho họ",
    ],
    a: 2,
    e: "An toàn tâm lý và sự ghi nhận là điều kiện để người ít nói đóng góp ý tưởng.",
  },
  {
    g: "Lãnh đạo",
    q: "Hành vi nào giúp xây dựng niềm tin tốt nhất?",
    o: [
      "Giữ lời hứa và nhất quán giữa lời nói với hành động",
      "Luôn đồng ý với nhân viên",
      "Không bao giờ thay đổi quyết định",
      "Chỉ tập trung vào kết quả",
    ],
    a: 0,
    e: "Niềm tin đến từ sự nhất quán và giữ cam kết, không phải từ việc chiều lòng hay cứng nhắc.",
  },
  {
    g: "Lãnh đạo",
    q: "Nền tảng của người lãnh đạo trong Hội Thánh trước hết là gì?",
    o: [
      "Khả năng nói trước đám đông",
      "Đời sống gương mẫu và tinh thần phục vụ",
      "Số năm tham gia sinh hoạt",
      "Mối quan hệ rộng",
    ],
    a: 1,
    e: "Lãnh đạo thuộc linh là dẫn dắt bằng gương sống và tinh thần đầy tớ, không phải bằng chức vụ hay tài ăn nói.",
  },
  {
    g: "Lãnh đạo",
    q: "Trưởng nhóm tế bào thấy nhóm ngày càng phụ thuộc vào mình. Hướng xử lý đúng là?",
    o: [
      "Giữ nguyên vì nhóm đang ổn định",
      "Từng bước giao việc, huấn luyện người kế cận để nhóm tự vận hành",
      "Giảm số buổi nhóm lại",
      "Chuyển nhóm cho người khác",
    ],
    a: 1,
    e: "Mục tiêu của người dẫn dắt là nhân cấp người phục vụ, không phải tạo sự lệ thuộc vào cá nhân mình.",
  },
  {
    g: "Lãnh đạo",
    q: "Một tín hữu mới rất nhiệt thành nhưng chưa hiểu rõ nề nếp Hội Thánh. Cách dẫn dắt phù hợp nhất?",
    o: [
      "Giao ngay vị trí phụ trách để giữ nhiệt huyết",
      "Kèm cặp, cho phục vụ việc phù hợp rồi mở rộng dần",
      "Để họ tự quan sát đến khi quen",
      "Hạn chế cho tham gia phục vụ",
    ],
    a: 1,
    e: "Nhiệt thành cao – kinh nghiệm thấp cần được hướng dẫn sát và giao việc tăng dần theo sự trưởng thành.",
  },
  {
    g: "Lãnh đạo",
    q: "Khi một ban ngành hoàn thành tốt công tác, người phụ trách nên?",
    o: [
      "Xem là việc đương nhiên",
      "Ghi nhận công khai đóng góp của cả nhóm và từng người",
      "Chỉ khen người nổi bật nhất",
      "Không khen để tránh kiêu ngạo",
    ],
    a: 1,
    e: "Ghi nhận đúng người, đúng việc nuôi dưỡng lòng sốt sắng phục vụ lâu dài.",
  },

  // ===== GIAO TIẾP =====
  {
    g: "Giao tiếp",
    q: "Nhân viên giải thích một vấn đề phức tạp. Người quản lý nên làm gì để lắng nghe chủ động?",
    o: [
      "Ngắt lời để tiết kiệm thời gian",
      "Vừa nghe vừa kiểm tra điện thoại",
      "Tóm tắt lại và đặt câu hỏi làm rõ",
      "Đưa ra giải pháp ngay",
    ],
    a: 2,
    e: "Lắng nghe chủ động gồm tập trung, tóm tắt lại và hỏi làm rõ trước khi phản hồi.",
  },
  {
    g: "Giao tiếp",
    q: "Khi giao một nhiệm vụ quan trọng, cách truyền đạt nào hiệu quả nhất?",
    o: [
      "Nói càng nhiều càng tốt",
      "Nêu rõ kết quả mong đợi, thời hạn và tiêu chuẩn",
      "Chỉ gửi tên nhiệm vụ",
      "Để nhân viên tự đoán ưu tiên",
    ],
    a: 1,
    e: "Thông điệp rõ ràng phải trả lời: làm gì, đạt mức nào, khi nào xong.",
  },
  {
    g: "Giao tiếp",
    q: "Khi cần góp ý về một lỗi, cách phản hồi phù hợp nhất là?",
    o: [
      "Chỉ trích tính cách của người làm",
      "Nói chung chung để tránh khó xử",
      "Nêu hành vi cụ thể, tác động và hướng cải thiện",
      "Phê bình trước cả nhóm",
    ],
    a: 2,
    e: "Phản hồi hiệu quả tập trung vào hành vi và tác động, kèm đề xuất cải thiện.",
  },
  {
    g: "Giao tiếp",
    q: "Một thành viên trong nhóm tế bào chia sẻ chuyện riêng tư. Người dẫn nhóm cần?",
    o: [
      "Kể lại cho nhóm khác để cùng cầu thay",
      "Giữ kín và chỉ chia sẻ khi được người đó cho phép",
      "Đăng lên nhóm chat để mọi người biết",
      "Xem như chuyện bình thường",
    ],
    a: 1,
    e: "Giữ bí mật riêng tư là điều kiện để nhóm trở thành nơi an toàn cho mọi người mở lòng.",
  },
  {
    g: "Giao tiếp",
    q: "Một tín hữu không hài lòng về cách tổ chức chương trình. Cách xử lý giao tiếp tốt nhất?",
    o: [
      "Tránh gặp cho đến khi họ nguôi",
      "Gặp riêng, lắng nghe đầy đủ rồi cùng tìm hướng điều chỉnh",
      "Phản bác ngay trong buổi nhóm",
      "Nhờ người khác trả lời thay",
    ],
    a: 1,
    e: "Gặp riêng và lắng nghe trước giúp hiểu đúng vấn đề và giữ được mối thông công.",
  },
  {
    g: "Giao tiếp",
    q: "Thông báo về một thay đổi lớn trong sinh hoạt Hội Thánh nên được truyền đạt thế nào?",
    o: [
      "Chỉ thông báo miệng một lần trong buổi nhóm",
      "Thông báo sớm, nêu lý do, qua nhiều kênh và có chỗ để hỏi đáp",
      "Chờ đến khi thay đổi đã xảy ra",
      "Chỉ báo cho ban chấp sự",
    ],
    a: 1,
    e: "Thay đổi lớn cần truyền thông sớm, giải thích lý do và mở kênh phản hồi để tránh hiểu lầm.",
  },
  {
    g: "Giao tiếp",
    q: "Dấu hiệu cho thấy phần hướng dẫn của bạn đã được hiểu đúng là?",
    o: [
      "Mọi người im lặng gật đầu",
      "Người nhận việc nói lại được nội dung và bước tiếp theo",
      "Bạn đã nói hết ý",
      "Buổi họp kết thúc sớm",
    ],
    a: 1,
    e: "Giao tiếp chỉ hoàn tất khi người nhận hiểu đúng; nói lại là cách kiểm chứng đơn giản nhất.",
  },

  // ===== LẬP KẾ HOẠCH =====
  {
    g: "Lập kế hoạch",
    q: "Mục tiêu nào gần với nguyên tắc SMART nhất?",
    o: [
      "Cải thiện dịch vụ thật tốt",
      "Tăng mức hài lòng khách hàng từ 80% lên 88% trong 3 tháng",
      "Cố gắng bán nhiều hơn",
      "Hoàn thành công việc sớm",
    ],
    a: 1,
    e: "SMART yêu cầu cụ thể, đo lường được và có mốc thời gian rõ ràng.",
  },
  {
    g: "Lập kế hoạch",
    q: "Khi có quá nhiều việc cần làm, bước phù hợp nhất là?",
    o: [
      "Làm việc dễ trước",
      "Ưu tiên theo mức độ quan trọng và khẩn cấp",
      "Làm tất cả cùng lúc",
      "Chờ đến khi có chỉ đạo",
    ],
    a: 1,
    e: "Ma trận quan trọng – khẩn cấp giúp phân bổ thời gian vào việc tạo giá trị cao nhất.",
  },
  {
    g: "Lập kế hoạch",
    q: "Một kế hoạch tốt nên được điều chỉnh khi nào?",
    o: [
      "Không bao giờ",
      "Chỉ khi dự án thất bại",
      "Khi dữ liệu, rủi ro hoặc điều kiện thực tế thay đổi đáng kể",
      "Mỗi ngày dù không có thay đổi",
    ],
    a: 2,
    e: "Kế hoạch là công cụ, cần cập nhật khi giả định hoặc điều kiện thay đổi.",
  },
  {
    g: "Lập kế hoạch",
    q: "Mục tiêu nào của nhóm tế bào là rõ ràng và đo lường được nhất?",
    o: [
      "Nhóm sẽ tăng trưởng mạnh mẽ",
      "Trong 6 tháng, nhóm có thêm 5 thành viên mới và huấn luyện 2 người dẫn nhóm",
      "Cố gắng mời thêm nhiều người",
      "Nhóm sẽ sốt sắng hơn",
    ],
    a: 1,
    e: "Mục tiêu phải cụ thể, có con số và mốc thời gian mới theo dõi được tiến trình.",
  },
  {
    g: "Lập kế hoạch",
    q: "Khi lên kế hoạch cho một chương trình lớn của Hội Thánh, việc cần làm sớm nhất là?",
    o: [
      "Đặt mục tiêu, phạm vi, nhân sự và ngân sách dự kiến",
      "Đặt tiệc và in ấn trước",
      "Chờ đến sát ngày cho linh động",
      "Giao hết cho một người lo",
    ],
    a: 0,
    e: "Xác định mục tiêu và nguồn lực trước giúp mọi khâu sau bám đúng trọng tâm và không vỡ ngân sách.",
  },
  {
    g: "Lập kế hoạch",
    q: "Lịch sinh hoạt năm của Hội Thánh nên được xây dựng thế nào?",
    o: [
      "Từng tháng quyết định dần",
      "Lập từ đầu năm, cân đối giữa các ban ngành và rà soát định kỳ",
      "Theo đề nghị phát sinh",
      "Lặp lại y hệt năm trước",
    ],
    a: 1,
    e: "Lịch năm giúp các ban ngành phối hợp, tránh trùng lịch và phân bổ nhân sự hợp lý.",
  },
  {
    g: "Lập kế hoạch",
    q: "Chuẩn bị phương án dự phòng cho một chương trình ngoài trời nên làm khi nào?",
    o: [
      "Khi trời bắt đầu mưa",
      "Ngay từ lúc lập kế hoạch",
      "Khi có người nhắc",
      "Không cần thiết",
    ],
    a: 1,
    e: "Nhận diện rủi ro sớm và có phương án dự phòng tốn ít công sức hơn nhiều so với xử lý sự cố.",
  },

  // ===== TỔ CHỨC & PHÂN CÔNG =====
  {
    g: "Tổ chức & phân công",
    q: "Nguyên tắc quan trọng nhất khi phân công công việc là?",
    o: [
      "Chia đều số lượng việc cho mọi người",
      "Giao việc phù hợp năng lực, trách nhiệm và mục tiêu",
      "Giao việc khó cho người bận nhất",
      "Người quản lý giữ mọi quyết định",
    ],
    a: 1,
    e: "Phân công hiệu quả là ghép đúng người – đúng việc – đúng trách nhiệm.",
  },
  {
    g: "Tổ chức & phân công",
    q: "Khi trao quyền cho nhân viên, người quản lý nên?",
    o: [
      "Giao việc rồi không theo dõi",
      "Nói rõ quyền hạn, kết quả mong đợi và điểm kiểm tra",
      "Kiểm soát từng bước nhỏ",
      "Chỉ giao những việc không quan trọng",
    ],
    a: 1,
    e: "Trao quyền đi kèm ranh giới rõ ràng và các điểm kiểm tra đã thống nhất.",
  },
  {
    g: "Tổ chức & phân công",
    q: "Hai thành viên đang làm trùng một nhiệm vụ. Cách xử lý tốt nhất là?",
    o: [
      "Để họ tự giải quyết",
      "Làm rõ vai trò, trách nhiệm và đầu mối phối hợp",
      "Hủy nhiệm vụ",
      "Giao thêm người thứ ba",
    ],
    a: 1,
    e: "Trùng việc là vấn đề vai trò; làm rõ vai trò và đầu mối sẽ chấm dứt chồng chéo.",
  },
  {
    g: "Tổ chức & phân công",
    q: "Phân công phục vụ trong Hội Thánh nên dựa trên điều gì là chính?",
    o: [
      "Ai rảnh nhất thì làm",
      "Ân tứ, khả năng và sự trưởng thành thuộc linh của từng người",
      "Thâm niên sinh hoạt",
      "Quan hệ thân quen",
    ],
    a: 1,
    e: "Phục vụ đúng ân tứ giúp người phục vụ bền sức và công việc đạt kết quả tốt hơn.",
  },
  {
    g: "Tổ chức & phân công",
    q: "Một người đang kiêm nhiệm quá nhiều ban ngành và bắt đầu kiệt sức. Cách xử lý đúng là?",
    o: [
      "Động viên cố gắng thêm",
      "Rà soát lại ưu tiên, san sẻ bớt việc và huấn luyện người thay thế",
      "Xem đó là sự hy sinh cần thiết",
      "Giao thêm để rèn luyện",
    ],
    a: 1,
    e: "Kiệt sức kéo dài làm tổn hại cả người phục vụ lẫn công việc; cần tái phân bổ và nhân cấp nhân sự.",
  },
  {
    g: "Tổ chức & phân công",
    q: "Khi nhóm tế bào phát triển quá đông, giải pháp tổ chức phù hợp nhất là?",
    o: [
      "Giữ nguyên cho đông vui",
      "Chuẩn bị người dẫn dắt và nhân cấp thành nhóm mới",
      "Hạn chế nhận thêm người",
      "Chuyển sang sinh hoạt trực tuyến",
    ],
    a: 1,
    e: "Nhóm quá đông làm giảm chiều sâu chăm sóc; nhân cấp có chuẩn bị là hướng phát triển lành mạnh.",
  },
  {
    g: "Tổ chức & phân công",
    q: "Ủy quyền trong công tác Hội Thánh KHÔNG có nghĩa là?",
    o: [
      "Giao việc kèm quyền quyết định trong phạm vi rõ ràng",
      "Tạo cơ hội cho người khác trưởng thành",
      "Đẩy toàn bộ trách nhiệm cuối cùng sang người được giao",
      "Giải phóng thời gian cho việc trọng yếu hơn",
    ],
    a: 2,
    e: "Người phụ trách vẫn chịu trách nhiệm chung về kết quả dù đã ủy quyền.",
  },

  // ===== RA QUYẾT ĐỊNH =====
  {
    g: "Ra quyết định",
    q: "Trước một quyết định quan trọng, bước đầu tiên nên là?",
    o: [
      "Chọn phương án quen thuộc",
      "Xác định vấn đề và thu thập thông tin liên quan",
      "Hỏi người đông ý kiến nhất",
      "Trì hoãn để tránh rủi ro",
    ],
    a: 1,
    e: "Quyết định tốt bắt đầu từ việc xác định đúng vấn đề và có dữ liệu.",
  },
  {
    g: "Ra quyết định",
    q: "Hai phương án có lợi ích tương đương. Người quản lý nên làm gì?",
    o: [
      "Chọn ngẫu nhiên",
      "So sánh rủi ro, nguồn lực và tác động dài hạn",
      "Chọn phương án đắt hơn",
      "Không quyết định",
    ],
    a: 1,
    e: "Khi lợi ích ngang nhau, tiêu chí phân định là rủi ro, nguồn lực và tác động dài hạn.",
  },
  {
    g: "Ra quyết định",
    q: "Sau khi đã ra quyết định, trách nhiệm của người quản lý là?",
    o: [
      "Đổ lỗi nếu kết quả không tốt",
      "Theo dõi kết quả và điều chỉnh khi có bằng chứng cần thiết",
      "Không xem lại quyết định",
      "Thay đổi liên tục",
    ],
    a: 1,
    e: "Quyết định cần được theo dõi và hiệu chỉnh dựa trên bằng chứng thực tế.",
  },
  {
    g: "Ra quyết định",
    q: "Một quyết định ảnh hưởng đến toàn Hội Thánh nên được đưa ra thế nào?",
    o: [
      "Do một người quyết cho nhanh",
      "Qua cầu nguyện, bàn bạc trong ban chấp sự và thông tin minh bạch cho hội chúng",
      "Theo ý kiến của người lớn tiếng nhất",
      "Chờ đến khi mọi người đều đồng ý tuyệt đối",
    ],
    a: 1,
    e: "Quyết định hệ trọng cần tiến trình tập thể và minh bạch để có sự đồng thuận và cam kết thực thi.",
  },
  {
    g: "Ra quyết định",
    q: "Khi nào nên để cả nhóm cùng tham gia quyết định?",
    o: [
      "Khi cần sự cam kết cao và nhóm nắm thông tin liên quan",
      "Khi tình huống khẩn cấp cần xử lý ngay",
      "Khi muốn tránh trách nhiệm cá nhân",
      "Trong mọi trường hợp",
    ],
    a: 0,
    e: "Tham gia làm tăng chất lượng và cam kết, nhưng không phù hợp với tình huống khẩn cấp.",
  },
  {
    g: "Ra quyết định",
    q: "Quyết định về tài chính của Hội Thánh cần nguyên tắc nào trước hết?",
    o: [
      "Tiết kiệm tối đa mọi khoản",
      "Minh bạch, có phê duyệt và báo cáo rõ ràng",
      "Do thủ quỹ tự quyết cho gọn",
      "Ưu tiên khoản nào cấp bách hơn",
    ],
    a: 1,
    e: "Tài chính dâng hiến đòi hỏi tính minh bạch, có quy trình phê duyệt và báo cáo định kỳ cho hội chúng.",
  },
  {
    g: "Ra quyết định",
    q: "Bạn đã đầu tư nhiều công sức cho một chương trình, nhưng dấu hiệu thực tế cho thấy khó đạt mục tiêu. Cách xử lý đúng đắn nhất?",
    o: [
      "Tiếp tục vì đã bỏ quá nhiều công sức",
      "Đánh giá lại lợi ích – chi phí từ hiện tại trở đi và sẵn sàng điều chỉnh hướng",
      "Giao cho người khác tiếp tục",
      "Giấu bớt thông tin bất lợi",
    ],
    a: 1,
    e: "Tránh bẫy chi phí chìm: chỉ lợi ích và chi phí tương lai mới liên quan đến quyết định hiện tại.",
  },

  // ===== GIẢI QUYẾT VẤN ĐỀ =====
  {
    g: "Giải quyết vấn đề",
    q: "Nhóm liên tục nộp báo cáo trễ. Việc đầu tiên nên làm là?",
    o: [
      "Phạt ngay",
      "Xác định vấn đề cụ thể và thu thập dữ liệu",
      "Thay toàn bộ nhóm",
      "Giảm yêu cầu chất lượng",
    ],
    a: 1,
    e: "Phải hiểu nguyên nhân trước khi áp dụng biện pháp.",
  },
  {
    g: "Giải quyết vấn đề",
    q: "Kỹ thuật “5 Whys” chủ yếu được dùng để?",
    o: [
      "Tìm người chịu lỗi",
      "Tìm nguyên nhân gốc rễ",
      "Tạo nhiều giải pháp sáng tạo",
      "Đánh giá ngân sách",
    ],
    a: 1,
    e: "5 Whys truy hỏi liên tiếp để đi từ triệu chứng đến nguyên nhân gốc.",
  },
  {
    g: "Giải quyết vấn đề",
    q: "Sau khi triển khai một giải pháp, bước nào quan trọng?",
    o: [
      "Kết thúc ngay",
      "Đo kết quả và rút kinh nghiệm",
      "Không nhắc lại vấn đề",
      "Chuyển trách nhiệm cho người khác",
    ],
    a: 1,
    e: "Đo lường và rút kinh nghiệm giúp giải pháp bền vững và không tái diễn vấn đề.",
  },
  {
    g: "Giải quyết vấn đề",
    q: "Số thành viên đi nhóm tế bào giảm dần trong 3 tháng. Bước đầu tiên nên là?",
    o: [
      "Đổi ngay địa điểm sinh hoạt",
      "Tìm hiểu nguyên nhân qua thăm hỏi và ghi nhận thực tế",
      "Nhắc nhở chung trong buổi nhóm",
      "Giảm số buổi nhóm",
    ],
    a: 1,
    e: "Phải hiểu vì sao người ta vắng (bận, tổn thương, thấy nhàm, đi lại khó) trước khi thay đổi cách làm.",
  },
  {
    g: "Giải quyết vấn đề",
    q: "Hai thành viên trong ban ngành có mâu thuẫn cá nhân, ảnh hưởng công việc chung. Hướng xử lý xây dựng nhất?",
    o: [
      "Chờ thời gian làm nguôi",
      "Gặp riêng từng người, rồi tạo cuộc trao đổi hòa giải tập trung vào vấn đề và lợi ích chung",
      "Công khai phân xử trước hội chúng",
      "Chuyển cả hai sang ban khác",
    ],
    a: 1,
    e: "Tách con người khỏi vấn đề và hòa giải riêng giữ được danh dự và mối thông công của cả hai bên.",
  },
  {
    g: "Giải quyết vấn đề",
    q: "Một vấn đề lặp lại nhiều lần trong công tác tổ chức cho thấy điều gì?",
    o: [
      "Người thực hiện thiếu cố gắng",
      "Nguyên nhân gốc chưa được xử lý, thường nằm ở quy trình hoặc vai trò",
      "Cần thay người phụ trách",
      "Chỉ là chuyện ngẫu nhiên",
    ],
    a: 1,
    e: "Vấn đề tái diễn hầu như luôn là vấn đề hệ thống, không phải vấn đề của một cá nhân.",
  },
  {
    g: "Giải quyết vấn đề",
    q: "Khi cần nhiều ý tưởng cho một chương trình mới, nguyên tắc quan trọng của buổi động não là?",
    o: [
      "Đánh giá và loại bỏ ý tưởng ngay khi vừa nêu",
      "Tạo ra thật nhiều phương án trước, đánh giá sau",
      "Chỉ người phụ trách được đề xuất",
      "Chọn ngay ý tưởng đầu tiên",
    ],
    a: 1,
    e: "Giai đoạn tạo ý tưởng cần tách khỏi giai đoạn phê bình để không dập tắt sự sáng tạo.",
  },

  // ===== TỔNG HỢP =====
  {
    g: "Tổng hợp",
    q: "Một dự án chậm tiến độ và tinh thần nhóm giảm. Cách tiếp cận tốt nhất là?",
    o: [
      "Chỉ tăng áp lực",
      "Làm rõ nguyên nhân, điều chỉnh kế hoạch và giao tiếp với nhóm",
      "Thay toàn bộ nhân sự",
      "Bỏ mục tiêu",
    ],
    a: 1,
    e: "Kết hợp phân tích nguyên nhân, điều chỉnh kế hoạch và giao tiếp minh bạch.",
  },
  {
    g: "Tổng hợp",
    q: "Một nhân viên có năng lực nhưng thường không rõ ưu tiên. Người quản lý nên?",
    o: [
      "Làm thay họ",
      "Làm rõ mục tiêu, thứ tự ưu tiên và quyền chủ động",
      "Kiểm tra mỗi 10 phút",
      "Không giao việc quan trọng",
    ],
    a: 1,
    e: "Vấn đề nằm ở sự rõ ràng về ưu tiên, không phải ở năng lực.",
  },
  {
    g: "Tổng hợp",
    q: "Dấu hiệu của quản lý hiệu quả nhất là?",
    o: [
      "Người quản lý luôn bận nhất",
      "Nhóm hiểu mục tiêu, phối hợp tốt và tạo ra kết quả bền vững",
      "Mọi quyết định đều do một người đưa ra",
      "Không có bất kỳ bất đồng nào",
    ],
    a: 1,
    e: "Hiệu quả quản lý thể hiện ở kết quả bền vững của nhóm, không ở mức độ bận rộn.",
  },
  {
    g: "Tổng hợp",
    q: "Dấu hiệu của một nhóm tế bào khỏe mạnh là gì?",
    o: [
      "Số người tham dự luôn đông nhất",
      "Thành viên được chăm sóc, trưởng thành và có người mới được huấn luyện dẫn dắt",
      "Buổi nhóm luôn kéo dài",
      "Mọi người đều im lặng nghe",
      "Không ai vắng mặt",
    ].slice(0, 4),
    a: 1,
    e: "Sức khỏe của nhóm đo bằng sự trưởng thành và khả năng nhân cấp, không chỉ bằng sĩ số.",
  },
  {
    g: "Tổng hợp",
    q: "Hội Thánh muốn mở thêm nhiều nhóm tế bào nhưng thiếu người dẫn dắt. Ưu tiên đúng nhất là?",
    o: [
      "Mở nhóm trước, tìm người sau",
      "Tập trung huấn luyện và cố vấn người dẫn dắt trước khi mở rộng",
      "Ghép nhiều nhóm làm một",
      "Tạm hoãn vô thời hạn",
    ],
    a: 1,
    e: "Tăng trưởng bền vững đi theo năng lực nhân sự; mở rộng vượt quá năng lực chăm sóc sẽ gây hụt hơi.",
  },
  {
    g: "Tổng hợp",
    q: "Chương trình thu hút rất đông người tham dự nhưng số người gắn bó lâu dài lại giảm. Cách đọc tình huống đúng nhất?",
    o: [
      "Không vấn đề gì vì số lượng vẫn tốt",
      "Kết quả bề nổi có thể đang che lấp thiếu hụt trong chăm sóc và môn đồ hóa; cần rà soát khâu tiếp nối",
      "Nên tổ chức thêm chương trình lớn",
      "Thay người phụ trách chương trình",
    ],
    a: 1,
    e: "Chỉ số tham dự là kết quả ngắn hạn; sự gắn bó và trưởng thành mới phản ánh sức khỏe dài hạn.",
  },
  {
    g: "Tổng hợp",
    q: "Bạn phải chọn giữa cách làm cho kết quả nhanh nhưng để lại lỗ hổng tổ chức, và cách làm chậm hơn nhưng bền vững. Nguyên tắc quyết định hợp lý nhất?",
    o: [
      "Luôn chọn cách nhanh",
      "Luôn chọn cách bền vững",
      "Căn cứ mức độ cấp bách, chi phí khắc phục về sau và cam kết kế hoạch bù đắp nếu chọn cách nhanh",
      "Bỏ phiếu ngẫu nhiên",
    ],
    a: 2,
    e: "Chọn nhanh là hợp lệ nếu ý thức được chi phí khắc phục và có kế hoạch xử lý phần còn thiếu.",
  },
  {
    g: "Tổng hợp",
    q: "Hai ban ngành trùng lịch và tranh nhau nhân sự nhiều lần trong năm. Giải pháp cấp hệ thống là?",
    o: [
      "Yêu cầu hai ban tự thu xếp",
      "Xây dựng lịch chung, quy tắc ưu tiên và cơ chế phối hợp nhân sự cho cả năm",
      "Kỷ luật trưởng ban",
      "Giảm bớt hoạt động của cả hai",
    ],
    a: 1,
    e: "Xung đột do thiết kế lịch và nguồn lực phải được xử lý ở cấp hệ thống, không chỉ ở quan hệ cá nhân.",
  },
];
